dist: xenial

branches:
  only:
    - master

addons:
  apt:
    packages:
      - docker-ce

install:
  # Semver Bash
  - sudo curl https://raw.githubusercontent.com/fsaintjacques/semver-tool/2.1.0/src/semver -o /usr/local/bin/semver && sudo chmod +x /usr/local/bin/semver
  - semver --version

  # Hub
  - sudo snap install hub --classic
  - hub --version

before_script:
  - export IMAGE_NAME='laudio/pyodbc'
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - git fetch --tags
  - git config --global user.name "Brother"
  - git config --global user.email "bot@laudio.com"

  # Generate .env.test file
  - cp .env.example .env.test
  - export $(egrep -v '^#' .env.test | xargs)

script:
  # Build docker images
  - make clean build

  # Spin up a mssql, pg & mysql database server containers
  - docker run --name test-mysql-server -e MYSQL_USER=${TEST_MYSQL_DB_USER} -e MYSQL_DATABASE=${TEST_MYSQL_DB_NAME} -e MYSQL_PASSWORD=${TEST_MYSQL_DB_PASSWORD} -d -p 3306:3306 mysql/mysql-server:latest
  - docker run --name test-mssql-server -e ACCEPT_EULA=Y -e SA_PASSWORD=${TEST_MSSQL_DB_PASSWORD} -d -p 1433:1433 microsoft/mssql-server-linux:2017-GA
  - docker run --name test-pg-server -e POSTGRES_USER=${TEST_PG_DB_USER} -e POSTGRES_DB=${TEST_PG_DB_NAME} -e POSTGRES_PASSWORD=${TEST_PG_DB_PASSWORD} -d -p 5432:5432 postgres
  - sleep 20s

  # Run tests
  - make test

  # Publish image to registry if merged into master.
  - ./release.sh

  # List docker images that are built (Just for information.)
  - docker images laudio/*

after_script:
  # Stop the running containers
  - docker stop test-mssql-server
  - docker stop test-pg-server
  - docker stop test-mysql-server
